title: "RACECAR Tutorial [ICRA '19]"
logo: /assets/img/racecar.jpg
description: "May 24, 2019 Montreal, Canada"
show_downloads: false

url: "https://fishberg.github.io"
baseurl: "/icra2019-workshop"

gems:
- jekyll-seo-tag
